### ISSUE TITLE
build paket deb bermasalah

### ISSUE THREAD

**Issue by hahn** [BlankOn/manokwari#100]
skrip debian manokwari masih bermasalah dengan meson. Apakah manokwari bisa dibuat paralel antara autotools dan meson?

**Comment by showcheap** [comment]
Ada log / step to reproduce pak @hahn ?

**Comment by showcheap** [comment]
meson cc @alunux

**Comment by hahn** [comment]
- pasang pakai meson (sesuai skrip di kabarlinux) berhasil
- pasang pakai langkah: 

```
./autogen.sh
make
```
 gagal. 

log galat: http://tempel.blankon.in/5693728

dicoba di tambora, debian sid, dan openSUSE (untuk meson)

**Comment by alunux** [comment]
@hahn seharusnya nggak ada kaitannya dengan Meson, karena galat terjadi saat menggunakan GNU Autotools.

**Comment by alunux** [comment]
Btw, issue-nya seperti yang sudah saya komen di sini https://github.com/BlankOn/manokwari/pull/93#issuecomment-336040475 dan sepertinya belum solved (tapi PR-nya udah di-merge ke master).

**Comment by showcheap** [comment]
Oo, ini terkait masalah command install ikut dijalankan ketika make.
Seperti yang dilaporkan pak @alunux kemarin di issue sebelumnya. Sedangkan
perintah make dijalankan dengan user non root maka permission denied. Nanti
di chek lagi pak, makasih laporanya.

Bisa pakai commit sebelum merge pull request terakhir untuk pemaketan.

**Comment by showcheap** [comment]
pak @hahn bisa cobain pull request saya di #101

**Comment by hahn** [comment]
ok pak @showcheap siap dicoba. Terima kasih :smiley:
