### ISSUE TITLE
gnome-autogen.sh missing

### ISSUE THREAD

**Issue by conqp** [BlankOn/manokwari#105]
Well, the `gnome-autogen.sh` called by `./autogen.sh` does not exist within this repo.
Version: 6ab1a9528a88eea443bee37253abbcc54da83a62

**Comment by showcheap** [comment]
The program 'gnome-autogen.sh' can be found in the following package:
  * gnome-common

**Comment by conqp** [comment]
Ah, I see. Thanks.
