### ISSUE TITLE
how to compile ?

### ISSUE THREAD

**Issue by v1nce** [BlankOn/manokwari#24]
How to compile ?

I downloaded the zipped version of GIT repository.

autogen.sh doesn't work (no gnome-autogen.sh)

I tried 
aclocal
autoconf
libtoolize
automake --add-missing
./configure
make
sudo make install

with no luck either

ubuntu 12.04

**Comment by herpiko** [comment]
@v1nce Could you provide the logs / error?

**Comment by v1nce** [comment]
gnome-autogen.sh was missing. I installed it using
sudo apt-get install gnome-common

libnotify was missing too. I installed it.
Now I'm stuck at the make stage:
...
/usr/bin/valac --vapidir ../vapi --pkg config --pkg atk --pkg x11 --pkg gdk-x11-3.0 --pkg gee-1.0 --pkg cairo --pkg gtk+-3.0 --pkg gio-unix-2.0 --pkg libgnome-menu-3.0 --pkg gdk-3.0 --pkg libwnck-3.0 --pkg unique-3.0 --pkg webkit-1.0 --pkg javascriptcore --pkg libsoup-2.4 --pkg libnotify   -C panel-item.vala main.vala panel-abstract-window.vala panel-window.vala panel-menu-box.vala panel-menu-content.vala panel-tray.vala panel-scrollable-content.vala panel-animated-adjustment.vala panel-clock.vala panel-places.vala panel-screen.vala utils.vala panel-hotkey.vala panel-session-manager.vala panel-menu-html.vala xdg-data.vala panel-user.vala panel-desktop.vala panel-desktop-html.vala panel-desktop-data.vala panel-calendar.vala animated-property.vala panel-shell.vala panel-socket.vala panel-xdg-properties.vala
panel-tray.vala:82.18-82.24: error: The symbol `X11' could not be found
      var win = (Gdk.X11.Window) invisible.get_window();
                 ^^^^^^^
panel-tray.vala:114.23-114.29: error: The symbol `X11' could not be found
      var xvisual = ((Gdk.X11.Visual)visual).get_xvisual(); 
                      ^^^^^^^
panel-tray.vala:116.26-116.32: error: The symbol `X11' could not be found
      var xid = (long) ((Gdk.X11.Window) invisible.get_window()).get_xid ();
                         ^^^^^^^
Compilation failed: 3 error(s), 0 warning(s)
make[2]: *** [manokwari_vala.stamp] Erreur 1
make[2]: quittant le répertoire « /tmp/manokwari-master/src »
make[1]: *** [all-recursive] Erreur 1
make[1]: quittant le répertoire « /tmp/manokwari-master »
make: *** [all] Erreur 2

**Comment by herpiko** [comment]
@v1nce 

Which version of vala are you using?

Try to change all `Gdk.X11.Window` string to `Gdk.X11Window` in `panel-tray.vala`.

**Comment by v1nce** [comment]
valac 0.22

I changed 

line 82
      var win = (Gdk.X11Window) invisible.get_window();

line 114-116
      var xvisual = ((Gdk.Visual)visual).get_xvisual(); <= looks like there's no X11.Visual so I used that
      ulong      data[1] ={ xvisual.get_visual_id() };
      var xid = (long) ((Gdk.X11Window) invisible.get_window()).get_xid ();

now the error log is

panel-item.vala:54.19-54.22: warning: Gtk.HBox has been deprecated since 3.2. Use Grid
panel-item.vala:63.39-63.43: warning: Gtk.Stock has been deprecated since 3.10
panel-item.vala:104.13-104.21: warning: Gtk.Widget.set_state has been deprecated since 3.0. Use set_state_flags
panel-item.vala:109.13-109.21: warning: Gtk.Widget.set_state has been deprecated since 3.0. Use set_state_flags
panel-item.vala:145.9-145.29: warning: Gtk.render_background has been deprecated since vala-0.16. Use StyleContext.render_background
panel-session-manager.vala:84.17-84.30: warning: implicit .begin is deprecated
panel-session-manager.vala:207.13-207.20: warning: implicit .begin is deprecated
panel-session-manager.vala:94.17-94.30: warning: implicit .begin is deprecated
panel-session-manager.vala:191.13-191.20: warning: implicit .begin is deprecated
panel-session-manager.vala:105.17-105.32: warning: implicit .begin is deprecated
panel-session-manager.vala:176.13-176.22: warning: implicit .begin is deprecated
panel-desktop.vala:63.42-63.53: warning: Access to static member `Gdk.Screen.width' with an instance reference
        stderr.printf("iii %d %d <--\n", screen.width(), screen.height());
                                         ^^^^^^^^^^^^
panel-desktop.vala:63.58-63.70: warning: Access to static member `Gdk.Screen.height' with an instance reference
        stderr.printf("iii %d %d <--\n", screen.width(), screen.height());
                                                         ^^^^^^^^^^^^^
panel-tray.vala:45.37-45.43: error: The name `X11' does not exist in the context of `Gdk'
        unowned X.Display display = Gdk.X11.get_default_xdisplay ();
                                    ^^^^^^^
panel-tray.vala:66.35-66.41: error: The name `X11' does not exist in the context of `Gdk'
      unowned X.Display display = Gdk.X11.get_default_xdisplay ();
                                  ^^^^^^^
panel-tray.vala:83.24-83.34: warning: Access to static member `Gdk.X11Window.get_xid' with an instance reference
      var xid = (long) win.get_xid ();
                       ^^^^^^^^^^^
panel-tray.vala:83.24-83.37: error: 1 missing arguments for `X.Window Gdk.X11Window.get_xid (Gdk.Window window)'
      var xid = (long) win.get_xid ();
                       ^^^^^^^^^^^^^^
panel-tray.vala:83.11-83.37: error: var declaration not allowed with non-typed initializer
      var xid = (long) win.get_xid ();
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
panel-tray.vala:89.29-89.35: error: The name `X11' does not exist in the context of `Gdk'
      event.data_l [0]    = Gdk.X11.get_server_time(win);
                            ^^^^^^^
panel-tray.vala:91.29-91.31: error: The name `xid' does not exist in the context of `PanelTray.setup_selection'
      event.data_l [2]    = xid;
                            ^^^
panel-tray.vala:97.32-97.34: error: The name `xid' does not exist in the context of `PanelTray.setup_selection'
      display.change_property (xid, display.intern_atom ("_NET_SYSTEM_TRAY_ORIENTATION,", false), X.XA_CARDINAL, 32, X.PropMode.Replace, (uchar[])data, 1);
                               ^^^
panel-tray.vala:110.35-110.41: error: The name `X11' does not exist in the context of `Gdk'
      unowned X.Display display = Gdk.X11.get_default_xdisplay ();
                                  ^^^^^^^
panel-tray.vala:114.21-114.52: error: The name `get_xvisual' does not exist in the context of `Gdk.Visual'
      var xvisual = ((Gdk.Visual)visual).get_xvisual(); 
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
panel-tray.vala:114.11-114.54: error: var declaration not allowed with non-typed initializer
      var xvisual = ((Gdk.Visual)visual).get_xvisual(); 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
panel-tray.vala:115.29-115.35: error: The name `xvisual' does not exist in the context of `PanelTray.new'
      ulong      data[1] ={ xvisual.get_visual_id() };
                            ^^^^^^^
panel-tray.vala:115.29-115.51: error: expression type not allowed as initializer
      ulong      data[1] ={ xvisual.get_visual_id() };
                            ^^^^^^^^^^^^^^^^^^^^^^^
panel-tray.vala:116.24-116.71: warning: Access to static member `Gdk.X11Window.get_xid' with an instance reference
      var xid = (long) ((Gdk.X11Window) invisible.get_window()).get_xid ();
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
panel-tray.vala:116.24-116.74: error: 1 missing arguments for `X.Window Gdk.X11Window.get_xid (Gdk.Window window)'
      var xid = (long) ((Gdk.X11Window) invisible.get_window()).get_xid ();
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
panel-tray.vala:116.11-116.74: error: var declaration not allowed with non-typed initializer
      var xid = (long) ((Gdk.X11Window) invisible.get_window()).get_xid ();
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
panel-tray.vala:118.32-118.34: error: The name `xid' does not exist in the context of `PanelTray.new'
      display.change_property (xid, visual_atom, X.XA_VISUALID, 32, X.PropMode.Replace,(uchar[])data, 1);
                               ^^^
panel-calendar.vala:16.23-16.26: warning: Gtk.VBox has been deprecated since 3.2. Use Box
panel-window.vala:834.9-834.25: warning: unhandled error `GLib.Error'
        indicator.show ();
        ^^^^^^^^^^^^^^^^^
panel-window.vala:839.21-839.72: warning: unhandled error `GLib.DBusError'
        var value = bus.get(BRIGHTNESS_PROP_IFACE, BRIGHTNESS_PROP_NAME);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
panel-window.vala:839.21-839.72: warning: unhandled error `GLib.IOError'
        var value = bus.get(BRIGHTNESS_PROP_IFACE, BRIGHTNESS_PROP_NAME);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
panel-window.vala:848.9-848.84: warning: unhandled error `GLib.DBusError'
        bus.set(BRIGHTNESS_PROP_IFACE, BRIGHTNESS_PROP_NAME, new Variant.int32(val));
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
panel-window.vala:848.9-848.84: warning: unhandled error `GLib.IOError'
        bus.set(BRIGHTNESS_PROP_IFACE, BRIGHTNESS_PROP_NAME, new Variant.int32(val));
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
panel-window.vala:853.21-853.72: warning: unhandled error `GLib.DBusError'
        var value = bus.get(BRIGHTNESS_PROP_IFACE, BRIGHTNESS_PROP_NAME);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
panel-window.vala:853.21-853.72: warning: unhandled error `GLib.IOError'
        var value = bus.get(BRIGHTNESS_PROP_IFACE, BRIGHTNESS_PROP_NAME);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
panel-window.vala:862.9-862.84: warning: unhandled error `GLib.DBusError'
        bus.set(BRIGHTNESS_PROP_IFACE, BRIGHTNESS_PROP_NAME, new Variant.int32(val));
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
panel-window.vala:862.9-862.84: warning: unhandled error `GLib.IOError'
        bus.set(BRIGHTNESS_PROP_IFACE, BRIGHTNESS_PROP_NAME, new Variant.int32(val));
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
panel-clock.vala:36.9-36.25: warning: Gtk.render_layout has been deprecated since vala-0.16. Use StyleContext.render_layout
Compilation failed: 15 error(s), 26 warning(s)
make[2]: *** [manokwari_vala.stamp] Erreur 1
make[2]: quittant le répertoire « /tmp/manokwari-master/src »
make[1]: *** [all-recursive] Erreur 1
make[1]: quittant le répertoire « /tmp/manokwari-master »
make: *** [all] Erreur 2

**Comment by herpiko** [comment]
You can try with the meson build option. As simple as : 

```
$ meson build && cd build
$ ninja
```

**Comment by v1nce** [comment]
autogen.sh failed because I got only gee0.8 and the tool needs gee1.0.

I tried meson build && cd build and it fails
Error during basic setup:

[Errno 2] No such file or directory: '/tmp/manokwari-master/build'

I give up. This tool probably needs a bleeding edge distro and not my ubuntu 16.04

**Comment by herpiko** [comment]
If you still want to try, there is ppa repository for manokwari. Please take a look here, https://launchpad.net/~dotovr/+archive/ubuntu/manokwari

**Comment by herpiko** [comment]
Ah sorry, I forgot that you want to compile instead of installing the package. :D

**Comment by alunux** [comment]
Well, we need to improve our documentation later :)

**Comment by brihadeesh** [comment]
I'm not sure the instructions on the website (http://manokwari.blankonlinux.or.id/) are too explicit about dependencies. Where can I find a list? I'm using Ubuntu 18.04
