### ISSUE TITLE
Manokwari not installed on Debian 8

### ISSUE THREAD

**Issue by Denissa89** [BlankOn/manokwari#65]
I'm trying to install a shell on Debian 8 Stable!
When sh sh autogen.sh generates an error:
configure: error: Package requirements (glib-2.0 >= 2.12.0 gobject-2.0 >= 2.12.0 gtk+-3.0 >= 3.0.8 atk >= 2.0.0 gee-1.0 >= 0.6.1 cairo >= 1.10.2 libgnome-menu-3.0 >= 2.30.5 libwnck-3.0 >= 3.0.0 unique-3.0 >= 3.0.0 webkitgtk-3.0 >= 1.3.0 x11 >= 1.6.0 libnotify >= 0.7.6) were not met:

No package 'libgnome-menu-3.0' found
No package 'libwnck-3.0' found
No package 'webkitgtk-3.0' found
No package 'libnotify' found

These packages are installed in the system

**Comment by herpiko** [comment]
Hi @Denissa89, We've updated the `dev-require.sh` file. You can use the script to install the required packages. Thank you.
