### ISSUE TITLE
Migrasi dari GNU Autotools ke Meson

### ISSUE THREAD

**Issue by alunux** [BlankOn/manokwari#68]
Apakah ada rencana untuk memigrasi _build_ _system_ yang digunakan oleh manokwari ke Meson? Selain sintak yang bersih dan mudah dimengerti, proses _build_ nya juga sangat cepat (_backend_ pakai ninja) dibanding pakai `make` dkk.

**Comment by herpiko** [comment]
> Apakah ada rencana untuk memigrasi *build* *system* yang digunakan oleh
> manokwari ke Meson? Selain sintak yang bersih dan mudah dimengerti, proses
> *build* nya juga sangat cepat (*backend* pakai ninja) dibanding pakai make
> dkk
>


Saya baru dengar soal Meson. Saya baca-baca dan kenalan dulu ya Pak.

Terima kasih atas usulan ini.



>

**Comment by alunux** [comment]
Beberapa proyek dibawah naungan proyek GNOME juga sudah melakukan migrasi ke Meson. Contoh proyek _desktop environment_ yang telah menggunakan Meson ada Budgie Desktop[1].

Terima kasih atas perhatiannya, Pak.https://github.com/budgie-desktop/budgie-desktop

**Comment by alunux** [comment]
@herpiko saya sudah melakukan porting ke Meson, Pak. Mungkin sebentar siang akan saya ajukan PR agar dapat dites oleh para pengembang.

**Comment by herpiko** [comment]
@herpiko <https://github.com/herpiko> saya sudah melakukan porting ke
> Meson, Pak. Mungkin sebentar siang akan saya ajukan PR agar dapat dites
> oleh para pengembang.
>


Wah! Ditunggu. Terima kasih!

**Comment by herpiko** [comment]
>
>
>
> Wah! Ditunggu. Terima kasih!
>


Saya baru terima PR-nya di Github. Terima kasih!

**Comment by herpiko** [comment]
@alunux Sudah merged ke master. :)

**Comment by alunux** [comment]
@herpiko Thanks!
