### ISSUE TITLE
gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by jingle0927** [BlankOn/manokwari#70]
deepin@deepin:~$ sudo add-apt-repository ppa:dotovr/manokwari
 Manokwari is a desktop shell for GNOME 3. It features combined Gtk+ and HTML5 frontend (Gtk+ is legacy here and would be replaced totally with HTML5 in the future). It is an evolution from a shell called blankon-panel.

Manokwari is used by BlankOn Linux.

http://manokwari.blankonlinux.or.id/
https://github.com/BlankOn/manokwari
https://github.com/BlankOn/manokwari/issues
https://github.com/BlankOn/manokwari/blob/master/DESIGN.md

 More info: https://launchpad.net/~dotovr/+archive/ubuntu/manokwari
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmp1pv5t4go/pubring.gpg' created
gpg: /tmp/tmp1pv5t4go/trustdb.gpg: trustdb created
gpg: key EF54E20E465FF80C: public key "Launchpad PPA for Mahyuddin Ramli" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
deepin@deepin:~$ sudo apt update && sudo apt install manokwari
命中:1 http://packages.deepin.com/deepin panda InRelease
忽略:2 http://ppa.launchpad.net/dotovr/manokwari/ubuntu artful InRelease     
错误:3 http://ppa.launchpad.net/dotovr/manokwari/ubuntu artful Release
  404  Not Found

**Comment by emhaye** [comment]
- Add gpg key mannual:
```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 334A1E592C0B54D747D61649EF54E20E465FF80C
```
- Distro codename change to `xenial` or `zesty`

**Comment by jingle0927** [comment]
deepin@deepin:~$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 334A1E592C0B54D747D61649EF54E20E465FF80C
Executing: /tmp/apt-key-gpghome.tcRfpCMKiB/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv 334A1E592C0B54D747D61649EF54E20E465FF80C
gpg: key EF54E20E465FF80C: public key "Launchpad PPA for Mahyuddin Ramli" imported
gpg: Total number processed: 1
gpg:               imported: 1

**Comment by jingle0927** [comment]
deepin@deepin:/etc/apt/sources.list.d$ sudo apt update && sudo apt install manokwari命中:1 http://packages.deepin.com/deepin panda InRelease
获取:2 http://ppa.launchpad.net/dotovr/manokwari/ubuntu xenial InRelease [24.3 kB]
获取:3 http://ppa.launchpad.net/dotovr/manokwari/ubuntu xenial/main amd64 Packages [1,856 B]
获取:4 http://ppa.launchpad.net/dotovr/manokwari/ubuntu xenial/main i386 Packages [1,856 B]

**Comment by jingle0927** [comment]
Thanks

**Comment by emhaye** [comment]
:+1:
