### ISSUE TITLE
ijin executable blankon-session hilang setelah make install

### ISSUE THREAD

**Issue by artemtech** [BlankOn/manokwari#71]
di github, berkas **blankon-session** di folder **files/bin** sudah executable. Namun setelah melakukan perintah **make** dan **make install**, berkas **blankon-session** di **/usr/bin/** menjadi tidak executable. Ini menyebabkan gagal masuk sesi manokwari ketika hendak login ke manokwari setelah melakukan build manual

log **.xsession-errors**:
/etc/lightdm/Xsession: baris 64: /usr/bin/blankon-session: Ijin ditolak
/etc/lightdm/Xsession: baris 64: exec: /usr/bin/blankon-session: tidak dapat menjalankan: Ijin ditolak

**Comment by herpiko** [comment]
@artemtech Ini terjadi di distribusi apa pak?

**Comment by artemtech** [comment]
@herpiko, arch pak

**Comment by showcheap** [comment]
@artemtech berdasar PR nomor #93 & #101 tiket ini bisa di close?

**Comment by artemtech** [comment]
bisa pak ..
closed #93  #101
