### ISSUE TITLE
berkas system/ tidak dipasang seluruhnya setelah make install

### ISSUE THREAD

**Issue by artemtech** [BlankOn/manokwari#72]
saat melakukan build manual,setelah menjalankan perintah **make install**, berkas yang tersalin di **/usr/lib/manokwari/system/** hanya 2 berkas html, sedangkan berkas lainnya di system/ tidak ikut tersalin. Hal ini menyebabkan tampilan manokwari menjadi kacau,

kutipan log **make install**:
``` Bash
make[2]: Memasuki direktori '/home/altintop/Dokumen/BlankOn/manokwari/system'
make[2]: Tidak ada yang harus dilakukan untuk 'install-exec-am'.
/usr/bin/mkdir -p '/usr/lib/manokwari/system'
/usr/bin/install -c -m 644 menu.html desktop.html '/usr/lib/manokwari/system'
```
tampilan setelah build manual:
https://artemtechblog.files.wordpress.com/2017/05/semula.jpg?w=300&h=225

**Comment by alunux** [comment]
@artemtech coba _build_ menggunakan Meson. Dukungan meson ada di branch `meson`[1]. Cara ini juga menyelesaikan masalah #71

[1] https://github.com/BlankOn/manokwari/tree/meson

**Comment by artemtech** [comment]
@alunux @herpiko , _build_ dengan Meson berhasil dilakukan, dan berkas terkait sudah ikut tersalin, 

masalah di #71 solved jika menggunakan Meson

**Comment by herpiko** [comment]
Tahan dulu tiketnya jangan ditutup. Yang make konvensional juga mesti kita dibenerin. :D

**Comment by alunux** [comment]
Tahapan build yang ada di skrip/resep autotools di manokwari kurang lengkap pak, ada beberapa instruksi yang belum ada. Ini sudah saya lihat sejak sebelum melakukan porting ke meson. Kalau pak @artemtech pernah otak-atik resep autotools (skrip autogen.sh, congigure.ac, makefile, dkk), mungkin bisa dilengkapin resepnya :D

**Comment by showcheap** [comment]
Sudah saya update di PR #93 tapi entah sudah mengikuti cara terbaik (best practice) atau belum :joy:

**Comment by showcheap** [comment]
@artemtech berdasar PR nomor #93 & #101 tiket ini bisa di close?

**Comment by artemtech** [comment]
bisa pak ...
closed #93 #101
