### ISSUE TITLE
How did u make a Desktop in HTML and dont have a product website -_-

### ISSUE THREAD

**Issue by stevenjc94** [BlankOn/manokwari#73]

**Comment by herpiko** [comment]
@stevenjc94 Hello!

Actually, we have one. 

http://manokwari.blankonlinux.or.id/

**Comment by stevenjc94** [comment]
ohh excellent then the next step is linking it on github its not easy to
find and it will be much more profitable to do so ( just my 2 cents ) thank
you

On Thu, Aug 24, 2017 at 8:08 PM, Herpiko Dwi Aguno <notifications@github.com

**Comment by herpiko** [comment]
@stevenjc94 Okay. Thank you for the suggestion. 😄
