### ISSUE TITLE
how to remove manokwari?

### ISSUE THREAD

**Issue by shadowwalker2718** [BlankOn/manokwari#75]
My multiscreen display doesn't work after installing manokwari. How to remove it? I could not find any document to remove it. It is more like a virus if it cannot be removed!

**Comment by herpiko** [comment]
Hi! Could you write first how did you install the Manokwari shell?

Is it from PPA, AUR, or compile manually?

**Comment by herpiko** [comment]
@shadowwalker2718 

Hi, I'll close this issue since there is no response till now. We'll update the documentation especially around compilation, installation and uninstallation. Thank you.
