### ISSUE TITLE
Just to say thanks.

### ISSUE THREAD

**Issue by azzamsa** [BlankOn/manokwari#76]
manokwari sudah saya cantumkan di [Awesome-Linux-Software](https://github.com/LewisVo/Awesome-Linux-Software#desktop-environments).

terimakasih banyak kepada seluruh pengembang BlankOn, untuk kontribusinya kepada masayarakat.

Terimakasih banyak.

**Comment by herpiko** [comment]
@azzamsa Sama-sama!
