### ISSUE TITLE
Upgrade to Webkit2 API

### ISSUE THREAD

**Issue by alunux** [BlankOn/manokwari#82]
`webkitgtk-3.0` (Webkit) has been considered deprecated and insecure for some time [1][2]. It even has already been removed from the repositories that will become Fedora 27 [3]. Need some idea about this from Manokwari or BlankOn development team. Thanks :)

[1] https://blogs.gnome.org/mcatanzaro/2016/02/01/on-webkit-security-updates
[2] https://blogs.gnome.org/mcatanzaro/2017/08/06/endgame-for-webkit-woes
[3] https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/AKVB363GFCHHJ5MTHGVYHYT6NLLTF5VM/

**Comment by herpiko** [comment]
@alunux Thank you for bringing this issue up. We'ill make this prioritized. Anyway, guys on R&D are wondering, would you like to join research team in BlankOn instead?

**Comment by alunux** [comment]
@herpiko Thank you, sir. With all due respect, i couldn't accept that invitation. First, i can't sign agreement like this [[1]](https://github.com/BlankOn/Uluwatu/blob/master/TEAM.md). Second, i'm not a long term contributor, i just fix small issues, make patches, and send them to upstream. Cooperative with upstream as much as possible. Third, i don't like (please, don't get me wrong about this) about technology behinds Manokwari, like Vala, GTK+, and friends, because their documentation isn't friendly to newbie like me. Well, i think this is just personal taste :) And finally, i don't like the design (architecture, especially web stuffs) [[2]](https://github.com/BlankOn/manokwari/blob/master/DESIGN.md). 

Again, with all due respect, i just want to be honest in my opinion. But overall, as user, i like it, that's why i contribute back to the project :)

**Comment by herpiko** [comment]
@alunux Thank you for your honest answer. We really appreciate your contributions. 😃 

There are some stickers and stuff that intended to be given to contributors. If you don't mind to send your address (to herpiko@gmail.com), I'll send you them as appreciation.

**Comment by herpiko** [comment]
@alunux Back to the topic, we'll discuss this internally. There is also another project that depends on`webkitgtk-3.0` like BlankOn Installer and Maleo.

**Comment by alunux** [comment]
@herpiko Wah, i really don't know that i will receive cool stuffs from BlankOn. Thank you so much, guys :D

**Comment by alunux** [comment]
Sekedar menambahkan referensi tambahan:
[1] Example of DOM access with WebKit2GTK - https://github.com/rschroll/webkitdom

**Comment by alunux** [comment]
I don't know about the progress of this issue. I'm trying to work on this, but still nothing is useful here. I will open a PR if it makes some progress.
https://github.com/alunux/manokwari/tree/webkit2

**Comment by alunux** [comment]
@herpiko Does this project accept C code?

**Comment by alunux** [comment]
@herpiko @showcheap Guys, could you create a new branch for this work? Thanks.

**Comment by showcheap** [comment]
@alunux you can create a PR to *develop* branch. Awesome works BTW

**Comment by herpiko** [comment]
@alunux Here you go https://github.com/BlankOn/manokwari/tree/webkit2

**Comment by alunux** [comment]
Not interested anymore.
