### ISSUE TITLE
Save web link on desktop

### ISSUE THREAD

**Issue by eastrader** [BlankOn/manokwari#99]
After using a while, I tried to save web links on my desktop as most systems allow. If I drag a web link over it replaces the desktop with that web page until I reboot. I have decided this is not the shell I want to use, but unable to remove. Here is how I installed it and need help to uninstall:
sudo add-apt-repository ppa:dotovr/manokwari

**Comment by herpiko** [comment]
@eastrader can you tell us your specific GNU/Linux distribution?

**Comment by eastrader** [comment]
Yes:
Linux version 4.10.0-38-generic (buildd@lgw01-amd64-059) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017

**Comment by eastrader** [comment]
Found this did the trick:
sudo apt autoremove manokwari
